window.NORTHSTAR_PRODUCTS = [
  {
    id: "aurora-lamp",
    name: "Aurora Glass Lamp",
    category: "Living",
    price: 129,
    id: "study-lamp",
    name: "Study Lamp",
    category: "Home",
    price: 1299,
    rating: 4.8,
    badge: "Best seller",
    badge: "Best Seller",
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80",
    summary: "Sculptural ambient lighting with soft diffusion for calm evening interiors.",
    description: "A hand-finished glass lamp with brass detailing, balanced to work as both a statement object and a reliable daily light source.",
    specs: ["Hand-blown shade", "Warm LED included", "2-year warranty"]
    summary: "A simple lamp for study table or bedroom use.",
    description: "This lamp gives good lighting for reading and working. It is useful for students and working professionals.",
    specs: ["LED light", "Low power use", "1 year warranty"]
  },
  {
    id: "trail-pack",
    name: "Trailday Utility Pack",
    category: "Travel",
    price: 94,
    id: "college-backpack",
    name: "College Backpack",
    category: "Bags",
    price: 1499,
    rating: 4.7,
    badge: "New drop",
    badge: "New",
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80",
    summary: "Compact travel companion with quick-access organization.",
    description: "Weather-resistant shell, padded laptop sleeve, and modular pockets make this an easy grab-and-go bag for commuting or weekend travel.",
    specs: ["18L capacity", "Water-resistant canvas", "Fits 14-inch laptop"]
    summary: "Useful bag for college, office, and travel.",
    description: "This backpack has enough space for books, a lunch box, and a laptop. It is comfortable to carry every day.",
    specs: ["Laptop pocket", "Water resistant", "Strong zip"]
  },
  {
    id: "cinder-mug",
    name: "Cinder Stoneware Set",
    id: "tea-cup-set",
    name: "Tea Cup Set",
    category: "Kitchen",
    price: 58,
    price: 799,
    rating: 4.9,
    badge: "Staff pick",
    badge: "Popular",
    image: "https://images.unsplash.com/photo-1514228742587-6b1558fcf93a?auto=format&fit=crop&w=900&q=80",
    summary: "Four tactile mugs for slow mornings and dinner hosting.",
    description: "Wheel-thrown stoneware with a matte charcoal glaze and comfortable handle profile designed for daily use.",
    specs: ["Set of 4", "Dishwasher safe", "Small-batch ceramic"]
    summary: "Set of cups for tea, coffee, and guests.",
    description: "A simple and stylish tea cup set for home use. Good for everyday kitchen use and small gatherings.",
    specs: ["Set of 4", "Easy to clean", "Ceramic finish"]
  },
  {
    id: "monarch-chair",
    name: "Monarch Lounge Chair",
    category: "Living",
    price: 320,
    id: "office-chair",
    name: "Office Chair",
    category: "Furniture",
    price: 4599,
    rating: 4.6,
    badge: "Premium",
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80",
    summary: "Low-profile lounge seating with soft boucle texture.",
    description: "Built with an ash wood frame and plush cushioning, the Monarch chair anchors reading nooks and reception corners.",
    specs: ["Solid ash frame", "Performance fabric", "Ships assembled"]
    summary: "Comfortable chair for office and study work.",
    description: "A soft and supportive chair that helps during long hours of work or online classes.",
    specs: ["Cushioned seat", "Strong frame", "Simple design"]
  },
  {
    id: "atlas-watch",
    name: "Atlas Field Watch",
    id: "wrist-watch",
    name: "Classic Wrist Watch",
    category: "Accessories",
    price: 175,
    price: 2199,
    rating: 4.5,
    badge: "Limited",
    badge: "Trending",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=80",
    summary: "Everyday timepiece built with crisp legibility and rugged details.",
    description: "A brushed steel field watch with sapphire crystal, luminous hands, and interchangeable strap system.",
    specs: ["Sapphire crystal", "50m water resistance", "Japanese movement"]
    summary: "Smart-looking watch for daily wear.",
    description: "This watch has a neat design and can be worn to college, office, or family functions.",
    specs: ["Water resistant", "Stylish strap", "Quartz movement"]
  },
  {
    id: "meadow-throw",
    name: "Meadow Woven Throw",
    category: "Living",
    price: 72,
    id: "sofa-cushion",
    name: "Sofa Cushion Set",
    category: "Home",
    price: 999,
    rating: 4.9,
    badge: "Popular",
    badge: "Top Rated",
    image: "https://images.unsplash.com/photo-1517705008128-361805f42e86?auto=format&fit=crop&w=900&q=80",
    summary: "Layered texture and warm tones for sofas and bed corners.",
    description: "Soft recycled cotton blend with a weighty drape, finished with a subtle stripe pattern and fringe edge.",
    specs: ["Recycled cotton", "Machine washable", "50 x 70 inches"]
    summary: "Soft cushions to improve home look and comfort.",
    description: "A good set of cushions for sofa or bed. It adds comfort and makes the room look better.",
    specs: ["Set of 2", "Soft fabric", "Easy maintenance"]
  }
];
